language: php

matrix:
  fast_finish: true
  include:
    - env: DM=~7.5
      php: 7
    - env: DM=~8.0
      php: 7.1
    - env: DM=@dev
      php: 7.2
    - env: DM=@dev
      php: 7.3
  allow_failures:
    - env: DM=@dev

sudo: false

install: travis_retry composer require "wikibase/data-model=$DM" --prefer-source

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikidata-feed"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"

cache:
  directories:
    - $HOME/.composer/cache
